name = "SimpleTypePrint"
uuid = "01919df6-f63c-417e-aa23-898e227d26ec"
authors = ["Jiayi Wei <wjydzh1@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
